Traceback (most recent call last):
  File "C:\Users\adelapuente\Desktop\jupBook\.venv\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\adelapuente\Desktop\jupBook\.venv\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\adelapuente\Desktop\jupBook\.venv\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\adelapuente\Desktop\jupBook\.venv\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\adelapuente\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\adelapuente\Desktop\jupBook\.venv\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\adelapuente\Desktop\jupBook\.venv\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\adelapuente\Desktop\jupBook\.venv\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def make_fig(figsize):
    from matplotlib import rcParams, cycler
    import matplotlib.pyplot as plt
    import numpy as np
    plt.ion()

    # Fixing random state for reproducibility
    np.random.seed(19680801)

    N = 10
    data = [np.logspace(0, 1, 100) + .2 * np.random.randn(100) + ii for ii in range(N)]
    data = np.array(data).T
    cmap = plt.cm.coolwarm
    rcParams['axes.prop_cycle'] = cycler(color=cmap(np.linspace(0, 1, N)))


    from matplotlib.lines import Line2D
    custom_lines = [Line2D([0], [0], color=cmap(0.), lw=4),
                    Line2D([0], [0], color=cmap(.5), lw=4),
                    Line2D([0], [0], color=cmap(1.), lw=4)]

    fig, ax = plt.subplots(figsize=figsize)
    lines = ax.plot(data)
    ax.legend(custom_lines, ['Cold', 'Medium', 'Hot'])
make_fig(figsize=(10, 5))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 25>[1;34m()[0m
[0;32m     23[0m     lines [38;5;241m=[39m ax[38;5;241m.[39mplot(data)
[0;32m     24[0m     ax[38;5;241m.[39mlegend(custom_lines, [[38;5;124m'[39m[38;5;124mCold[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mMedium[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mHot[39m[38;5;124m'[39m])
[1;32m---> 25[0m [43mmake_fig[49m[43m([49m[43mfigsize[49m[38;5;241;43m=[39;49m[43m([49m[38;5;241;43m10[39;49m[43m,[49m[43m [49m[38;5;241;43m5[39;49m[43m)[49m[43m)[49m

Input [1;32mIn [1][0m, in [0;36mmake_fig[1;34m(figsize)[0m
[0;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mmake_fig[39m(figsize):
[1;32m----> 2[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m rcParams, cycler
[0;32m      3[0m     [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m      4[0m     [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

[1;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

